// method + modifier + ingredient + product = awesome new buzz-worthy drink

let textComponents = {
    "methods": {
        "default": [
            "",
            "",
            "Small batch",
            "Smoked",
            // Add new items at the end to prevent links breaking
        ],
        "beer": [
            "",
            "",
            "",
            "Freeze-distilled",
            "Small batch",
            "Smoked",
            "Wild fermented",
            // Add new items at the end to prevent links breaking
        ],
        "cocktails": [
            "hastily thrown together by a minimum wage earner with no real training or motivation for the job at hand",
            "depth-charged into a pint of beer",
            "garnished with a cocktail onion",
            "garnished with a maraschino cherry",
            "garnished with an olive",
            "garnished with two olives",
            "garnished with three olives",
            "poured directly into your mouth from a height of 3 feet",
            "served in a balloon glass",
            "served in a coupe glass",
            "served in a champagne flute",
            "served in a crystal tumbler",
            "served in a frozen glass rinsed with absinthe",
            "served in a glass rimmed with salt",
            "served in a highball glass",
            "served in a martini glass",
            "served in a pint glass",
            "served in some kind of awful novelty glassware",
            "served over crushed ice",
            "set alight",
            "shaken",
            "shaken, not stirred",
            "slopped inexpertly into the first glass that comes to hand",
            "stirred",
            "stirred, not shaken",
            "stirred slowly for 10 minutes",
            "with a coffee bean floating on top",
            "with a paper cocktail umbrella (but not in an ironic way)",
            "with a paper cocktail umbrella (in an ironic way)",
            "with a plastic monkey hanging from the rim of the glass",
            "with a shard of crispy, maple-glazed bacon",
            "with a single, giant ice cube",
            "with a slice of apple",
            "with a slice of lemon",
            "with a slice of orange",
            "with a twist of grapefruit zest",
            "with a twist of lemon zest",
            "with a twist of lime zest",
            "with a twist of orange zest",
            "with a wedge of lime",
        ]
    },
    "modifiers":{
        "default": [
            "",
            "alcohol-free",
            "artisan",
            "artisanal",
            "barrel-aged",
            "biodynamic",
            "british",
            "caramelised",
            "caffeinated",
            "CBD-infused",
            "decaffeinated",
            "dry-hopped",
            "double dry-hopped",
            "ethically sourced",
            "fermented",
            "gluten-free",
            "heritage",
            "locally sourced",
            "low carb",
            "organic",
            "own-brand",
            "sustainable",
            "trappist",
            "vegan",
            "vegetarian",
            "zero calorie",
            // add new items at the end to prevent links breaking
        ],
        "beer": [
            "",
            "alcohol-free",
            "barrel-aged",
            "biodynamic",
            "caffeinated",
            "CBD-infused",
            "dry-hopped",
            "double dry-hopped",
            "ethically sourced",
            "gluten-free",
            "low carb",
            "organic",
            "own-brand",
            "sustainable",
            "trappist",
            "vegan",
            "vegetarian",
            "zero calorie",
            // add new items at the end to prevent links breaking
        ],
        "cocktails": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Blood temperature",
            "Frozen",
            "Ice cold",
            "Lightly chilled",
            "Smoked",
            "Spiced",
            "Warm",
        ]
    },
    "ingredients": {
        "default": [
            "",
            "apple",
            "basil",
            "beetroot",
            "blonde caramel",
            "bloody mary",
            "buckwheat",
            "candied bacon",
            "chive flower",
            "chive",
            "cider apple vinegar",
            "clam",
            "coffee caramel",
            "corriander seed",
            "corriander",
            "cucumber",
            "earl grey tea",
            "espresso martini",
            "fennel",
            "fig leaf",
            "fig",
            "gin and tonic",
            "golden beetroot",
            "heather honey",
            "honey",
            "lapsang souchong tea",
            "lion's mane mushroom",
            "maitake mushroom",
            "marmite",
            "mars bar",
            "miso",
            "mushroom",
            "olive oil",
            "olive",
            "pandan leaf",
            "pear",
            "pomegranate molasses",
            "pomegranate seed",
            "pornstar martini",
            "prosecco",
            "pumpkin spice",
            "pumpkin",
            "red wine vinegar",
            "salted caramel",
            "scotch bonnet",
            "seaweed",
            "shitake mushroom",
            "spelt",
            "strawberry",
            "tomato",
            "tonka bean",
            "vanilla pod",
            "vanilla",
            "vermouth",
            "whey",
            "white chocolate",
            // add new items at the end to prevent links breaking
        ],
        "beer": [
            "",
            "basil",
            "candied bacon",
            "chocolate",
            "cherry",
            "chilli",
            "coffee",
            "earl grey tea",
            "espresso",
            "gin and tonic",
            "heather honey",
            "honey",
            "lapsang souchong tea",
            "lion's mane mushroom",
            "maitake mushroom",
            "mango",
            "marmite",
            "mars bar",
            "miso",
            "mushroom",
            "passionfruit",
            "peach",
            "peanut butter",
            "pumpkin",
            "pumpkin spice",
            "salted caramel",
            "sea buckhorn",
            "seaweed",
            "scotch bonnet",
            "shitake mushroom",
            "spelt",
            "strawberry",
            "tonka bean",
            "vanilla",
            "white chocolate",
            // add new items at the end to prevent links breaking
        ],
        "cocktails": [
            "",
            "absinthe",
            "agave nectar",
            "akvavit",
            "amaretto",
            "American whiskey",
            "an unidentifiable, luridly coloured liqueur",
            "Angostura bitters",
            "Aperol",
            "apple juice",
            "arak",
            "armagnac",
            "arrack",
            "awamori",
            "baijiu",
            "balsamic vinegar",
            "basil",
            "beetroot juice",
            "Benedictine",
            "blanco tequila",
            "blue curaçao",
            "borovička",
            "bourbon",
            "brandy",
            "cachaça",
            "calvados",
            "Campari",
            "Canadian whisky",
            "candied bacon",
            "Cava",
            "Chambord",
            "Champagne",
            "cheap blended whiskey",
            "cheap tequila",
            "cider apple vinegar",
            "cider",
            "clam juice",
            "coconut water",
            "coffee bean",
            "cognac",
            "Cointreau",
            "corriander seed",
            "corriander",
            "Courvoisier",
            "cranberry juice",
            "cream",
            "crème de cassis",
            "crème de menthe",
            "crème de mûre",
            "crème de violette",
            "cucumber",
            "damassine",
            "damson gin",
            "dark rum",
            "demerara sugar cube",
            "demerara syrup",
            "dry sherry",
            "dry vermouth",
            "earl grey tea",
            "eau-de-vie",
            "elderflower liqueur",
            "espresso",
            "falernum",
            "Fernet-Branca",
            "fig leaf syrup",
            "fig",
            "Freya Birch Spirit",
            "Gaoling liquor",
            "geist",
            "genever",
            "gin",
            "ginger beer",
            "ginger syrup",
            "ginger wine",
            "Grand Marnier",
            "green Chartreuse",
            "grenadine",
            "heather honey",
            "Herbsaint",
            "himbeergeist",
            "honey",
            "horilka",
            "Irish whiskey",
            "Jack Daniel's",
            "Jagermeister",
            "Japanese whisky",
            "jenever",
            "Kahlua",
            "Kaoliang liquor",
            "kirsch",
            "lapsang souchong tea",
            "lemon juice",
            "Lillet blanc",
            "lime juice",
            "London dry gin",
            "lychee juice",
            "Mamajuana",
            "ManX Spirit",
            "Maotai",
            "maraschino liqueur",
            "marmite",
            "mescal",
            "Metaxa",
            "mezcal",
            "Midori",
            "mirin",
            "miso",
            "navy rum",
            "neutral grain spirit",
            "Ògógóró",
            "Old Tom gin",
            "olive oil",
            "olive",
            "orange bitters",
            "ouso",
            "pálenka",
            "pandan leaf syrup",
            "passion fruit puree",
            "peach schnapps",
            "pear juice",
            "Pernod",
            "Peychaud's bitters",
            "pickle brine",
            "pineapple juice",
            "pisco",
            "Plymouth gin",
            "Poire Williams",
            "poitín",
            "pomegranate molasses",
            "pomegranate seed",
            "prosecco",
            "pumpkin spice",
            "raki",
            "red wine vinegar",
            "reposado tequila",
            "rum",
            "rye whiskey",
            "sake",
            "salted caramel",
            "samohon",
            "schnapps",
            "scotch bonnet",
            "Scotch whisky",
            "shaojiu",
            "shōchū",
            "shōchū",
            "simple syrup",
            "singani",
            "single malt whiskey",
            "slivovitz",
            "sloe gin",
            "soju",
            "sorghum liquor",
            "strawberry",
            "sweet vermouth",
            "Tabasco",
            "Tennessee whiskey",
            "tequila",
            "Texas whiskey",
            "Tia Maria",
            "tomato juice",
            "tonka bean",
            "törkölypálinka",
            "triple sec",
            "Ţuică",
            "vanilla pod",
            "vanilla",
            "vermouth",
            "violet liqueur",
            "vodka",
            "whey",
            "whipped cream",
            "whiskey",
            "whisky",
            "white chocolate",
            "white peach puree",
            "white rum",
            "Williamine",
            "Worcestershire sauce",
            // add new items at the end to prevent links breaking
        ],
    },
    "products": {
        "default": [
            "ale",
            "beer",
            "gin",
            "hard seltzer",
            "infusion",
            "IPA",
            "kombucha",
            "mild",
            "new england IPA",
            "pastry stout",
            "pastry sour",
            "seltzer",
            "soda",
            "sour ale",
            "stout",
            "triple IPA",
            "vodka",
            "west coast IPA",
            // add new items at the end to prevent links breaking
        ],
        "beer": [
            // start - brewers association style list
            // taken from https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/
            // british origin ale styles
            "ordinary bitter",
            "special bitter",
            "best bitter",
            "extra special bitter",
            "scottish-style light ale",
            "scottish-style heavy ale",
            "scottish-style export ale",
            "english-style summer ale",
            "classic english-style pale ale",
            "british-style india pale ale",
            "strong ale",
            "old ale",
            "english-style pale mild ale",
            "english-style dark mild ale",
            "english-style brown ale",
            "brown porter",
            "robust porter",
            "sweet stout",
            "cream stout",
            "oatmeal stout",
            "scotch ale",
            "wee heavy",
            "british-style imperial stout",
            "british-style barley wine ale",
            //irish origin ale styles
            "irish-style red ale",
            "classic irish-style dry stout",
            "export-style stout",
            //north american origin ale styles
            "golden ale",
            "blonde ale",
            "session india pale ale",
            "american-style amber/red ale",
            "american-style pale ale",
            "juicy pale ale",
            "hazy pale ale",
            "american-style strong pale ale",
            "juicy strong pale ale",
            "hazy strong pale ale",
            "american-style india pale ale",
            "west coast-style india pale ale",
            "juicy india pale ale",
            "hazy india pale ale",
            "american-belgo-style ale",
            "american-style brown ale",
            "american-style black ale",
            "american-style stout",
            "american-style imperial porter",
            "american-style imperial stout",
            "double hoppy red ale",
            "imperial red ale",
            "american-style imperial india pale ale",
            "american-style double india pale ale",
            "juicy double india pale ale",
            "juicy imperial india pale ale",
            "hazy double india pale ale",
            "hazy imperial india pale ale",
            "american-style barley wine ale",
            "american-style wheat wine ale",
            "smoke porter",
            "american-style sour ale",
            "american-style fruited sour ale",
            //german origin ale styles
            "german-style koelsch",
            "german-style altbier",
            "berliner-style weisse",
            "leipzig-style gose",
            "contemporary-style gose",
            "south german-style hefeweizen",
            "south german-style kristal weizen",
            "german-style leichtes weizen",
            "south german-style bernsteinfarbenes weizen",
            "south german-style dunkel weizen",
            "south german-style weizenbock",
            "german-style rye ale",
            "bamberg-style weiss rauchbier",
            //belgian and french origin ale styles
            "belgian-style table beer",
            "belgian-style session ale",
            "belgian-style speciale belge",
            "belgian-style blonde ale",
            "belgian-style strong blonde ale",
            "belgian-style strong dark ale",
            "belgian-style dubbel",
            "belgian-style tripel",
            "belgian-style quadrupel",
            "belgian-style witbier",
            "classic french & belgian-style saison",
            "specialty saison",
            "french-style bière de garde",
            "belgian-style flanders oud bruin",
            "belgian-style flanders oud red ale",
            "belgian-style lambic",
            "traditional belgian-style gueuze",
            "contemporary belgian-style spontaneous fermented ale",
            "belgian-style fruit lambic",
            //other origin ale styles
            "grodziskie",
            "adambier",
            "dutch-style kuit",
            "dutch-style kuyt",
            "dutch-style koyt",
            "international-style pale ale",
            "classic australian-style pale ale",
            "australian-style pale ale",
            "new zealand-style pale ale",
            "new zealand-style india pale ale",
            "finnish-style sahti",
            "swedish-style gotlandsdricke",
            "breslau-style schoeps",
            //european origin lager styles
            "german-style leichtbier",
            "german-style pilsener",
            "bohemian-style pilsener",
            "munich-style helles",
            "dortmunder/european-style export",
            "vienna-style lager",
            "franconian-style rotbier",
            "german-style maerzen",
            "german-style oktoberfest/wiesn",
            "munich-style dunkel",
            "european-style dark lager",
            "german-style schwarzbier",
            "bamberg-style helles rauchbier",
            "bamberg-style maerzen rauchbier",
            "bamberg-style bock rauchbier",
            "german-style heller bock/maibock",
            "traditional german-style bock",
            "german-style doppelbock",
            "german-style eisbock",
            //north american origin lager styles
            "american-style lager",
            "contemporary american-style lager",
            "american-style light lager",
            "contemporary american-style light lager",
            "american-style pilsener",
            "contemporary american-style pilsener",
            "american-style india pale lager",
            "american-style malt liquor",
            "american-style amber lager",
            "american-style maerzen/oktoberfest",
            "american-style dark lager",
            //other origin lager styles
            "australasian light lager",
            "latin american light lager",
            "tropical-style light lager",
            "international-style pilsener",
            "baltic-style porter",
            "hybrid/mixed lager",
            "hybrid/mixed ale",
            //all origin hybrid/mixed lagers or ale
            "session beer",
            "american-style cream ale",
            "california common beer",
            "kentucky common beer",
            "american-style fruit beer",
            "fruit wheat beer",
            "belgian-style fruit beer",
            "field beer",
            "pumpkin spice beer",
            "pumpkin/squash beer",
            "chocolate beer",
            "cocoa beer",
            "dessert stout",
            "pastry stout",
            "coffee beer",
            "chili pepper beer",
            "herb and spice beer",
            "specialty beer",
            "specialty honey beer",
            "rye beer",
            "brett beer",
            "mixed-culture brett beer",
            "ginjo beer",
            "sake-yeast beer",
            "fresh hop beer",
            "wood- and barrel-aged sour beer",
            "aged beer",
            "experimental beer",
            "experimental india pale ale",
            "historical beer",
            "wild beer",
            "smoke beer",
            "strong ale",
            "strong lager",
            "malt beverage",
            // END - Brewers association style list
            // Add new items at the end to prevent links breaking
        ],
        "cocktails": [
            "",
            "and coke",
            "and lemonade",
            "and soda",
            "and tonic",
            "bloody mary",
            "boulevardier",
            "cocktail",
            "cup",
            "daiquiri",
            "fizz",
            "flip",
            "gibson",
            "gimlet",
            "manhattan",
            "margarita",
            "martini",
            "mojito",
            "negroni",
            "old fashioned",
            "on the rocks",
            "punch",
            "shot",
            "slush",
            "spritz",
            "whiskey sour",
            "with ginger ale",
            "with orange juice",
        ]
    },
    "hops": {
        "default": [],
        "beer": [
            // START hops taken from https://www.hopslist.com/hops/
            //Bittering Hops
            "Admiral",
            "Agnus",
            "Apollo",
            "Banner",
            "Bitter Gold",
            "Bravo",
            "Brewer's Gold",
            "Brewer's Gold (US)",
            "Bullion",
            "Bullion 10A",
            "California Cluster",
            "Chelan",
            "Cluster (AUS)",
            "Comet",
            "Eastern Gold",
            "Eroica",
            "Feux-Coeur",
            "Galena",
            "Kitamidori",
            "Magnum",
            "Magnum (US)",
            "Millennium",
            "Newport",
            "Outeniqua",
            "Pacific Gem",
            "Pacific Sunrise",
            "Pilot",
            "Pride of Ringwood",
            "Satus®",
            "Sorachi Ace",
            "Southern Brewer",
            "Southern Star",
            "Sovereign",
            "Summit™",
            "Super Pride",
            "Symphony",
            "Tillicum®",
            "Toyomidori",
            "Warrior®",
            "Yakima Cluster",
            "Zenith",
            "Zeus",
            //Aroma Hops
            "Ahil",
            "Ahtanum™",
            "Amarillo™ VGXP01",
            "Amethyst",
            "Aquila",
            "Aramis",
            "Atlas",
            "Backa",
            "Bianca",
            "Blato",
            "Blisk",
            "Boadicea",
            "BOR",
            "Bramling",
            "Canadian Redvine",
            "Canterbury Whitebine",
            "Cascade (Argentina)",
            "Cascade (Australia)",
            "Cekin",
            "Celeia",
            "Cobb",
            "Columbia",
            "Crystal",
            "Dana",
            "Defender",
            "Density",
            "Dunav",
            "Early Bird",
            "Early Green",
            "Early Prolific",
            "Early Promise",
            "East Kent Golding",
            "Eastern Green",
            "Eastwell Golding",
            "El Dorado ®",
            "Ella",
            "Elsaesser",
            "Equinox",
            "First Choice",
            "Fuggle",
            "Fuggle (US)",
            "Fuggle H",
            "Fuggle N",
            "Furano Ace",
            "Gargoyle",
            "Golden Star",
            "Golding (BC)",
            "Golding (US)",
            "Groene Bel",
            "Hallertau",
            "Hallertau (NZ)",
            "Hallertau (US)",
            "Hallertau Blanc",
            "Hallertauer Gold",
            "Hallertauer Tradition",
            "Helga",
            "Hersbrucker",
            "Hersbrucker E",
            "Hersbrucker Pure",
            "Hersbrucker Red-Stem",
            "Hüll Melon",
            "Hybrid-2",
            "Ivanhoe",
            "Janus",
            "Jester®",
            "Keyworth's Early",
            "Keyworth's Midseason",
            "Kohatu®",
            "Landhopfen",
            "Liberty",
            "Lubelska",
            "Lubelska-Pulawy",
            "Lucan",
            "Mandarina Bavaria",
            "Mathon",
            "Motueka",
            "Mount Hood",
            "Mount Rainier",
            "Nadwislanska",
            "Nordgaard",
            "Olympic",
            "Omega",
            "Pacific Jade",
            "Pacifica",
            "Palisade®",
            "Petham Golding",
            "Pocket Talisman",
            "Precoce de Bourgogne",
            "Premiant",
            "Progress",
            "Record",
            "Red Earth",
            "Riwaka",
            "Saaz",
            "Saaz (US)",
            "Santiam",
            "Saphir",
            "Saxon",
            "Serebrianka",
            "Shinshuwase",
            "Sladek",
            "Sonnet",
            "Spalt",
            "Spalter Select",
            "Star",
            "Strisselspalt",
            "Styrian Golding",
            "Summer",
            "Sun",
            "Sunbeam",
            "Sunshine",
            "Sussex",
            "Sylva",
            "Tahoma",
            "Tardif de Bourgogne",
            "Teamaker",
            "Tettnanger",
            "Tettnanger (Swiss)",
            "Tettnanger A",
            "Tettnanger B",
            "Tolhurst",
            "Topaz",
            "Triskel",
            "Ultra",
            "Vanguard",
            "Viking",
            "Vojvodina",
            "Wai-iti",
            "Whitbread Golding",
            "Willamette",
            "Willamette (AUS)",
            "Wuerttemberger",
            "Zlatan",
            "Zythos®",
            //Dual Use Hops
            "African Queen",
            "Alliance",
            "Amallia",
            "Apolon",
            "Aurora",
            "Azacca ®",
            "Bate's Brewer",
            "Belma®",
            "Blue Northern Brewer",
            "Bobek",
            "Bouclier",
            "Bramling Cross",
            "Buket",
            "Buzz Bullets",
            "Calicross",
            "Caliente",
            "Calypso",
            "Cascade (NZ)",
            "Cascade (US)",
            "Cashmere",
            "Centennial",
            "Cerera",
            "Challenger",
            "Chinook",
            "Cicero",
            "Citra®",
            "Cluster (US)",
            "Coigneau",
            "Columbus",
            "Delta",
            "Dr Rudi",
            "Eureka",
            "Falconer's Flight®",
            "Fantasia®",
            "First Gold",
            "Fuggle Tetraploid",
            "Galaxy ®",
            "Glacier",
            "Goldings (NZ)",
            "Green Bullet",
            "Greensburg",
            "Hallertauer Taurus",
            "Herald",
            "Herkules",
            "Horizon",
            "Hüller Bitterer",
            "Kirin II",
            "Legacy®",
            "Marynka",
            "Melba",
            "Merkur",
            "Mosaic ®",
            "MultiHead",
            "Nelson Sauvin",
            "Neo1",
            "Neoplanta",
            "Northdown",
            "Northern Brewer (GR)",
            "Northern Brewer (UK)",
            "Northern Brewer (US)",
            "Nugget",
            "Opal",
            "Orbit",
            "Orion",
            "Perle",
            "Perle (US)",
            "Phoenix",
            "Pilgrim",
            "Pioneer",
            "Polaris",
            "Pride of Kent",
            "Rakau",
            "Simcoe®",
            "Smaragd",
            "Smooth Cone",
            "Southern Cross",
            "Southern Promise",
            "Sterling",
            "Sticklebract",
            "Styrian Gold",
            "Styrian Wolf",
            "Talisman",
            "Target",
            "Tettnanger (US)",
            "Universal",
            "Vic Secret",
            "Vital",
            "Waimea",
            "Wakatu",
            "Willow Creek",
            "Yakima Gold",
            "Yeoman",
            // END hops taken from https://www.hopslist.com/hops/
            "Sabro",
        ],
        "cocktails": [],
    }
}